require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InfoproductosController do

  # This should return the minimal set of attributes required to create a valid
  # Infoproducto. As you add validations to Infoproducto, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "titulo" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InfoproductosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all infoproductos as @infoproductos" do
      infoproducto = Infoproducto.create! valid_attributes
      get :index, {}, valid_session
      assigns(:infoproductos).should eq([infoproducto])
    end
  end

  describe "GET show" do
    it "assigns the requested infoproducto as @infoproducto" do
      infoproducto = Infoproducto.create! valid_attributes
      get :show, {:id => infoproducto.to_param}, valid_session
      assigns(:infoproducto).should eq(infoproducto)
    end
  end

  describe "GET new" do
    it "assigns a new infoproducto as @infoproducto" do
      get :new, {}, valid_session
      assigns(:infoproducto).should be_a_new(Infoproducto)
    end
  end

  describe "GET edit" do
    it "assigns the requested infoproducto as @infoproducto" do
      infoproducto = Infoproducto.create! valid_attributes
      get :edit, {:id => infoproducto.to_param}, valid_session
      assigns(:infoproducto).should eq(infoproducto)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Infoproducto" do
        expect {
          post :create, {:infoproducto => valid_attributes}, valid_session
        }.to change(Infoproducto, :count).by(1)
      end

      it "assigns a newly created infoproducto as @infoproducto" do
        post :create, {:infoproducto => valid_attributes}, valid_session
        assigns(:infoproducto).should be_a(Infoproducto)
        assigns(:infoproducto).should be_persisted
      end

      it "redirects to the created infoproducto" do
        post :create, {:infoproducto => valid_attributes}, valid_session
        response.should redirect_to(Infoproducto.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved infoproducto as @infoproducto" do
        # Trigger the behavior that occurs when invalid params are submitted
        Infoproducto.any_instance.stub(:save).and_return(false)
        post :create, {:infoproducto => { "titulo" => "invalid value" }}, valid_session
        assigns(:infoproducto).should be_a_new(Infoproducto)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Infoproducto.any_instance.stub(:save).and_return(false)
        post :create, {:infoproducto => { "titulo" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested infoproducto" do
        infoproducto = Infoproducto.create! valid_attributes
        # Assuming there are no other infoproductos in the database, this
        # specifies that the Infoproducto created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Infoproducto.any_instance.should_receive(:update_attributes).with({ "titulo" => "MyString" })
        put :update, {:id => infoproducto.to_param, :infoproducto => { "titulo" => "MyString" }}, valid_session
      end

      it "assigns the requested infoproducto as @infoproducto" do
        infoproducto = Infoproducto.create! valid_attributes
        put :update, {:id => infoproducto.to_param, :infoproducto => valid_attributes}, valid_session
        assigns(:infoproducto).should eq(infoproducto)
      end

      it "redirects to the infoproducto" do
        infoproducto = Infoproducto.create! valid_attributes
        put :update, {:id => infoproducto.to_param, :infoproducto => valid_attributes}, valid_session
        response.should redirect_to(infoproducto)
      end
    end

    describe "with invalid params" do
      it "assigns the infoproducto as @infoproducto" do
        infoproducto = Infoproducto.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Infoproducto.any_instance.stub(:save).and_return(false)
        put :update, {:id => infoproducto.to_param, :infoproducto => { "titulo" => "invalid value" }}, valid_session
        assigns(:infoproducto).should eq(infoproducto)
      end

      it "re-renders the 'edit' template" do
        infoproducto = Infoproducto.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Infoproducto.any_instance.stub(:save).and_return(false)
        put :update, {:id => infoproducto.to_param, :infoproducto => { "titulo" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested infoproducto" do
      infoproducto = Infoproducto.create! valid_attributes
      expect {
        delete :destroy, {:id => infoproducto.to_param}, valid_session
      }.to change(Infoproducto, :count).by(-1)
    end

    it "redirects to the infoproductos list" do
      infoproducto = Infoproducto.create! valid_attributes
      delete :destroy, {:id => infoproducto.to_param}, valid_session
      response.should redirect_to(infoproductos_url)
    end
  end

end
